// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8hipkzZNLdrUjxw3yc8TtsJHq9ZWIU-c',
    appId: '1:790557394932:web:12742543ae27eb4b9ddba1',
    messagingSenderId: '790557394932',
    projectId: 'wordpress-f63ea',
    authDomain: 'wordpress-f63ea.firebaseapp.com',
    storageBucket: 'wordpress-f63ea.firebasestorage.app',
    measurementId: 'G-E7SJP826WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFqf-sNjFVzWCYw2L8SaFU7fr_hf564aM',
    appId: '1:790557394932:android:bc1cc5506c8495da9ddba1',
    messagingSenderId: '790557394932',
    projectId: 'wordpress-f63ea',
    storageBucket: 'wordpress-f63ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKkBOBHYZ2yjgBgXHOFt-HBeETbURrgW4',
    appId: '1:790557394932:ios:91149350b522692d9ddba1',
    messagingSenderId: '790557394932',
    projectId: 'wordpress-f63ea',
    storageBucket: 'wordpress-f63ea.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKkBOBHYZ2yjgBgXHOFt-HBeETbURrgW4',
    appId: '1:790557394932:ios:91149350b522692d9ddba1',
    messagingSenderId: '790557394932',
    projectId: 'wordpress-f63ea',
    storageBucket: 'wordpress-f63ea.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8hipkzZNLdrUjxw3yc8TtsJHq9ZWIU-c',
    appId: '1:790557394932:web:9f004f45f66732029ddba1',
    messagingSenderId: '790557394932',
    projectId: 'wordpress-f63ea',
    authDomain: 'wordpress-f63ea.firebaseapp.com',
    storageBucket: 'wordpress-f63ea.firebasestorage.app',
    measurementId: 'G-F5XK2XE0L3',
  );
}
